package com.manoinfoways.model;
// Generated Mar 22, 2012 6:27:47 PM by Hibernate Tools 3.4.0.CR1



/**
 * ClinicMetadata generated by hbm2java
 */
public class ClinicMetadata  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -5183229614995060700L;
	private Integer metaDataId;
     private ClinicData clinicData;
     private String transcriptionsInchargeName;
     private String transcriptionsInchargeEmail;
     private String transcriptionInchargePhnNo;
     private String trancriptionInchargeFaxNo;
     private String transcriptionInchargeAddress;
     private String technicalPersonName;
     private String technicalPersonEmail;
     private String technicalPersonPhnNo;
     private String technicalPersonFaxNo;
     private String technicalPersonAddress;
     private String softwarePersonName;
     private String softwarePersonEmail;
     private String softwarePersonPhnNo;
     private String softwarePersonCellNo;
     private String softwarePersonAddress;
     private String emailForPatientList;
     private String emailForInvoices;

    public ClinicMetadata() {
    }

    public ClinicMetadata(ClinicData clinicData, String transcriptionsInchargeName, String transcriptionsInchargeEmail, String transcriptionInchargePhnNo, String trancriptionInchargeFaxNo, String transcriptionInchargeAddress, String technicalPersonName, String technicalPersonEmail, String technicalPersonPhnNo, String technicalPersonFaxNo, String technicalPersonAddress, String softwarePersonName, String softwarePersonEmail, String softwarePersonPhnNo, String softwarePersonCellNo, String softwarePersonAddress, String emailForPatientList, String emailForInvoices) {
       this.clinicData = clinicData;
       this.transcriptionsInchargeName = transcriptionsInchargeName;
       this.transcriptionsInchargeEmail = transcriptionsInchargeEmail;
       this.transcriptionInchargePhnNo = transcriptionInchargePhnNo;
       this.trancriptionInchargeFaxNo = trancriptionInchargeFaxNo;
       this.transcriptionInchargeAddress = transcriptionInchargeAddress;
       this.technicalPersonName = technicalPersonName;
       this.technicalPersonEmail = technicalPersonEmail;
       this.technicalPersonPhnNo = technicalPersonPhnNo;
       this.technicalPersonFaxNo = technicalPersonFaxNo;
       this.technicalPersonAddress = technicalPersonAddress;
       this.softwarePersonName = softwarePersonName;
       this.softwarePersonEmail = softwarePersonEmail;
       this.softwarePersonPhnNo = softwarePersonPhnNo;
       this.softwarePersonCellNo = softwarePersonCellNo;
       this.softwarePersonAddress = softwarePersonAddress;
       this.emailForPatientList = emailForPatientList;
       this.emailForInvoices = emailForInvoices;
    }
   
    public Integer getMetaDataId() {
        return this.metaDataId;
    }
    
    public void setMetaDataId(Integer metaDataId) {
        this.metaDataId = metaDataId;
    }
    public ClinicData getClinicdata() {
        return this.clinicData;
    }
    
    public void setClinicdata(ClinicData clinicData) {
        this.clinicData = clinicData;
    }
    public String getTranscriptionsInchargeName() {
        return this.transcriptionsInchargeName;
    }
    
    public void setTranscriptionsInchargeName(String transcriptionsInchargeName) {
        this.transcriptionsInchargeName = transcriptionsInchargeName;
    }
    public String getTranscriptionsInchargeEmail() {
        return this.transcriptionsInchargeEmail;
    }
    
    public void setTranscriptionsInchargeEmail(String transcriptionsInchargeEmail) {
        this.transcriptionsInchargeEmail = transcriptionsInchargeEmail;
    }
    public String getTranscriptionInchargePhnNo() {
        return this.transcriptionInchargePhnNo;
    }
    
    public void setTranscriptionInchargePhnNo(String transcriptionInchargePhnNo) {
        this.transcriptionInchargePhnNo = transcriptionInchargePhnNo;
    }
    public String getTrancriptionInchargeFaxNo() {
        return this.trancriptionInchargeFaxNo;
    }
    
    public void setTrancriptionInchargeFaxNo(String trancriptionInchargeFaxNo) {
        this.trancriptionInchargeFaxNo = trancriptionInchargeFaxNo;
    }
    public String getTranscriptionInchargeAddress() {
        return this.transcriptionInchargeAddress;
    }
    
    public void setTranscriptionInchargeAddress(String transcriptionInchargeAddress) {
        this.transcriptionInchargeAddress = transcriptionInchargeAddress;
    }
    public String getTechnicalPersonName() {
        return this.technicalPersonName;
    }
    
    public void setTechnicalPersonName(String technicalPersonName) {
        this.technicalPersonName = technicalPersonName;
    }
    public String getTechnicalPersonEmail() {
        return this.technicalPersonEmail;
    }
    
    public void setTechnicalPersonEmail(String technicalPersonEmail) {
        this.technicalPersonEmail = technicalPersonEmail;
    }
    public String getTechnicalPersonPhnNo() {
        return this.technicalPersonPhnNo;
    }
    
    public void setTechnicalPersonPhnNo(String technicalPersonPhnNo) {
        this.technicalPersonPhnNo = technicalPersonPhnNo;
    }
    public String getTechnicalPersonFaxNo() {
        return this.technicalPersonFaxNo;
    }
    
    public void setTechnicalPersonFaxNo(String technicalPersonFaxNo) {
        this.technicalPersonFaxNo = technicalPersonFaxNo;
    }
    public String getTechnicalPersonAddress() {
        return this.technicalPersonAddress;
    }
    
    public void setTechnicalPersonAddress(String technicalPersonAddress) {
        this.technicalPersonAddress = technicalPersonAddress;
    }
    public String getSoftwarePersonName() {
        return this.softwarePersonName;
    }
    
    public void setSoftwarePersonName(String softwarePersonName) {
        this.softwarePersonName = softwarePersonName;
    }
    public String getSoftwarePersonEmail() {
        return this.softwarePersonEmail;
    }
    
    public void setSoftwarePersonEmail(String softwarePersonEmail) {
        this.softwarePersonEmail = softwarePersonEmail;
    }
    public String getSoftwarePersonPhnNo() {
        return this.softwarePersonPhnNo;
    }
    
    public void setSoftwarePersonPhnNo(String softwarePersonPhnNo) {
        this.softwarePersonPhnNo = softwarePersonPhnNo;
    }
    public String getSoftwarePersonCellNo() {
        return this.softwarePersonCellNo;
    }
    
    public void setSoftwarePersonCellNo(String softwarePersonCellNo) {
        this.softwarePersonCellNo = softwarePersonCellNo;
    }
    public String getSoftwarePersonAddress() {
        return this.softwarePersonAddress;
    }
    
    public void setSoftwarePersonAddress(String softwarePersonAddress) {
        this.softwarePersonAddress = softwarePersonAddress;
    }
    public String getEmailForPatientList() {
        return this.emailForPatientList;
    }
    
    public void setEmailForPatientList(String emailForPatientList) {
        this.emailForPatientList = emailForPatientList;
    }
    public String getEmailForInvoices() {
        return this.emailForInvoices;
    }
    
    public void setEmailForInvoices(String emailForInvoices) {
        this.emailForInvoices = emailForInvoices;
    }




}


