package com.manoinfoways.model;

// Generated Mar 14, 2012 4:42:37 PM by Hibernate Tools 3.4.0.CR1

/**
 * ClinicRequirements generated by hbm2java
 */
public class ClinicRequirements implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -805303097700271104L;
	private Integer clinicRequirementId;
	private ClinicData clinicData;
	private String clinicRequirement1;
	private String clinicRequirement2;
	private String clinicRequirement3;
	private String clinicRequirement4;
	private String clinicRequirement5;
	private String clinicRequirement6;
	private String clinicRequirement7;
	private String clinicRequirement8;
	private String clinicRequirement9;
	private String clinicRequirement10;
	private String clinicRequirement11;
	private String clinicRequirement12;
	private String clinicRequirement13;
	private String clinicRequirement14;
	private String clinicRequirement15;

	public ClinicRequirements() {
	}

	public ClinicRequirements(ClinicData clinicData) {
		this.clinicData = clinicData;
	}

	public ClinicRequirements(ClinicData clinicData, String clinicRequirement1,
			String clinicRequirement2, String clinicRequirement3,
			String clinicRequirement4, String clinicRequirement5,
			String clinicRequirement6, String clinicRequirement7,
			String clinicRequirement8, String clinicRequirement9,
			String clinicRequirement10, String clinicRequirement11,
			String clinicRequirement12, String clinicRequirement13,
			String clinicRequirement14, String clinicRequirement15) {
		this.clinicData = clinicData;
		this.clinicRequirement1 = clinicRequirement1;
		this.clinicRequirement2 = clinicRequirement2;
		this.clinicRequirement3 = clinicRequirement3;
		this.clinicRequirement4 = clinicRequirement4;
		this.clinicRequirement5 = clinicRequirement5;
		this.clinicRequirement6 = clinicRequirement6;
		this.clinicRequirement7 = clinicRequirement7;
		this.clinicRequirement8 = clinicRequirement8;
		this.clinicRequirement9 = clinicRequirement9;
		this.clinicRequirement10 = clinicRequirement10;
		this.clinicRequirement11 = clinicRequirement11;
		this.clinicRequirement12 = clinicRequirement12;
		this.clinicRequirement13 = clinicRequirement13;
		this.clinicRequirement14 = clinicRequirement14;
		this.clinicRequirement15 = clinicRequirement15;
	}

	public Integer getClinicRequirementId() {
		return this.clinicRequirementId;
	}

	public void setClinicRequirementId(Integer clinicRequirementId) {
		this.clinicRequirementId = clinicRequirementId;
	}

	public ClinicData getClinicdata() {
		return this.clinicData;
	}

	public void setClinicdata(ClinicData clinicData) {
		this.clinicData = clinicData;
	}

	public String getClinicRequirement1() {
		return this.clinicRequirement1;
	}

	public void setClinicRequirement1(String clinicRequirement1) {
		this.clinicRequirement1 = clinicRequirement1;
	}

	public String getClinicRequirement2() {
		return this.clinicRequirement2;
	}

	public void setClinicRequirement2(String clinicRequirement2) {
		this.clinicRequirement2 = clinicRequirement2;
	}

	public String getClinicRequirement3() {
		return this.clinicRequirement3;
	}

	public void setClinicRequirement3(String clinicRequirement3) {
		this.clinicRequirement3 = clinicRequirement3;
	}

	public String getClinicRequirement4() {
		return this.clinicRequirement4;
	}

	public void setClinicRequirement4(String clinicRequirement4) {
		this.clinicRequirement4 = clinicRequirement4;
	}

	public String getClinicRequirement5() {
		return this.clinicRequirement5;
	}

	public void setClinicRequirement5(String clinicRequirement5) {
		this.clinicRequirement5 = clinicRequirement5;
	}

	public String getClinicRequirement6() {
		return this.clinicRequirement6;
	}

	public void setClinicRequirement6(String clinicRequirement6) {
		this.clinicRequirement6 = clinicRequirement6;
	}

	public String getClinicRequirement7() {
		return this.clinicRequirement7;
	}

	public void setClinicRequirement7(String clinicRequirement7) {
		this.clinicRequirement7 = clinicRequirement7;
	}

	public String getClinicRequirement8() {
		return this.clinicRequirement8;
	}

	public void setClinicRequirement8(String clinicRequirement8) {
		this.clinicRequirement8 = clinicRequirement8;
	}

	public String getClinicRequirement9() {
		return this.clinicRequirement9;
	}

	public void setClinicRequirement9(String clinicRequirement9) {
		this.clinicRequirement9 = clinicRequirement9;
	}

	public String getClinicRequirement10() {
		return this.clinicRequirement10;
	}

	public void setClinicRequirement10(String clinicRequirement10) {
		this.clinicRequirement10 = clinicRequirement10;
	}

	public String getClinicRequirement11() {
		return this.clinicRequirement11;
	}

	public void setClinicRequirement11(String clinicRequirement11) {
		this.clinicRequirement11 = clinicRequirement11;
	}

	public String getClinicRequirement12() {
		return this.clinicRequirement12;
	}

	public void setClinicRequirement12(String clinicRequirement12) {
		this.clinicRequirement12 = clinicRequirement12;
	}

	public String getClinicRequirement13() {
		return this.clinicRequirement13;
	}

	public void setClinicRequirement13(String clinicRequirement13) {
		this.clinicRequirement13 = clinicRequirement13;
	}

	public String getClinicRequirement14() {
		return this.clinicRequirement14;
	}

	public void setClinicRequirement14(String clinicRequirement14) {
		this.clinicRequirement14 = clinicRequirement14;
	}

	public String getClinicRequirement15() {
		return this.clinicRequirement15;
	}

	public void setClinicRequirement15(String clinicRequirement15) {
		this.clinicRequirement15 = clinicRequirement15;
	}

}
