package com.manoinfoways.model;
// Generated Mar 22, 2012 6:27:47 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * ClinicConnectionDetails generated by hbm2java
 */
public class ClinicConnectionDetails  implements java.io.Serializable {


     private Integer clinicConnectionId;
     private ClinicData clinicData;
     private String clinicConnectionType;
     private String userName;
     private String password;
     private String systemLoginUserName;
     private String systemLoginPassword;
     private String typeOfSoftware;
     private String mailOrFtpforVoiceFiles;
     private String recorderUsed;
     private String typeOfVoiceFiles;
     private String voiceFilesPath;
     private String transcriptsPath;
     private Date folderDate;

    public ClinicConnectionDetails() {
    }

	
    public ClinicConnectionDetails(ClinicData clinicData) {
        this.clinicData = clinicData;
    }
    public ClinicConnectionDetails(ClinicData clinicData, String clinicConnectionType, String userName, String password, String systemLoginUserName, String systemLoginPassword, String typeOfSoftware, String mailOrFtpforVoiceFiles, String recorderUsed, String typeOfVoiceFiles, String voiceFilesPath, String transcriptsPath, Date folderDate) {
       this.clinicData = clinicData;
       this.clinicConnectionType = clinicConnectionType;
       this.userName = userName;
       this.password = password;
       this.systemLoginUserName = systemLoginUserName;
       this.systemLoginPassword = systemLoginPassword;
       this.typeOfSoftware = typeOfSoftware;
       this.mailOrFtpforVoiceFiles = mailOrFtpforVoiceFiles;
       this.recorderUsed = recorderUsed;
       this.typeOfVoiceFiles = typeOfVoiceFiles;
       this.voiceFilesPath = voiceFilesPath;
       this.transcriptsPath = transcriptsPath;
       this.folderDate = folderDate;
    }
   
    public Integer getClinicConnectionId() {
        return this.clinicConnectionId;
    }
    
    public void setClinicConnectionId(Integer clinicConnectionId) {
        this.clinicConnectionId = clinicConnectionId;
    }
    public ClinicData getClinicdata() {
        return this.clinicData;
    }
    
    public void setClinicdata(ClinicData clinicData) {
        this.clinicData = clinicData;
    }
    public String getClinicConnectionType() {
        return this.clinicConnectionType;
    }
    
    public void setClinicConnectionType(String clinicConnectionType) {
        this.clinicConnectionType = clinicConnectionType;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getSystemLoginUserName() {
        return this.systemLoginUserName;
    }
    
    public void setSystemLoginUserName(String systemLoginUserName) {
        this.systemLoginUserName = systemLoginUserName;
    }
    public String getSystemLoginPassword() {
        return this.systemLoginPassword;
    }
    
    public void setSystemLoginPassword(String systemLoginPassword) {
        this.systemLoginPassword = systemLoginPassword;
    }
    public String getTypeOfSoftware() {
        return this.typeOfSoftware;
    }
    
    public void setTypeOfSoftware(String typeOfSoftware) {
        this.typeOfSoftware = typeOfSoftware;
    }
    public String getMailOrFtpforVoiceFiles() {
        return this.mailOrFtpforVoiceFiles;
    }
    
    public void setMailOrFtpforVoiceFiles(String mailOrFtpforVoiceFiles) {
        this.mailOrFtpforVoiceFiles = mailOrFtpforVoiceFiles;
    }
    public String getRecorderUsed() {
        return this.recorderUsed;
    }
    
    public void setRecorderUsed(String recorderUsed) {
        this.recorderUsed = recorderUsed;
    }
    public String getTypeOfVoiceFiles() {
        return this.typeOfVoiceFiles;
    }
    
    public void setTypeOfVoiceFiles(String typeOfVoiceFiles) {
        this.typeOfVoiceFiles = typeOfVoiceFiles;
    }
    public String getVoiceFilesPath() {
        return this.voiceFilesPath;
    }
    
    public void setVoiceFilesPath(String voiceFilesPath) {
        this.voiceFilesPath = voiceFilesPath;
    }
    public String getTranscriptsPath() {
        return this.transcriptsPath;
    }
    
    public void setTranscriptsPath(String transcriptsPath) {
        this.transcriptsPath = transcriptsPath;
    }
    public Date getFolderDate() {
        return this.folderDate;
    }
    
    public void setFolderDate(Date folderDate) {
        this.folderDate = folderDate;
    }




}


