package com.manoinfoways.model;

// Generated Apr 13, 2012 2:07:43 PM by Hibernate Tools 3.4.0.CR1

/**
 * TranscriberDoctorPriority generated by hbm2java
 */
public class TranscriberDoctorPriority implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3608608878906098615L;
	private Integer priorityId;
	private TranscriberData transcriberData;
	private TranscriberTypeData transcriberTypeData;
	private DoctorData doctorData;
	private Integer priority;

	public TranscriberDoctorPriority() {
	}

	public TranscriberDoctorPriority(TranscriberData transcriberData,
			TranscriberTypeData transcriberTypeData, DoctorData doctorData,
			Integer priority) {
		this.transcriberData = transcriberData;
		this.transcriberTypeData = transcriberTypeData;
		this.doctorData = doctorData;
		this.priority = priority;
	}

	public Integer getPriorityId() {
		return this.priorityId;
	}

	public void setPriorityId(Integer priorityId) {
		this.priorityId = priorityId;
	}

	public TranscriberData getTranscriberdata() {
		return this.transcriberData;
	}

	public void setTranscriberdata(TranscriberData transcriberData) {
		this.transcriberData = transcriberData;
	}

	public TranscriberTypeData getTranscribertypedata() {
		return this.transcriberTypeData;
	}

	public void setTranscribertypedata(TranscriberTypeData transcriberTypeData) {
		this.transcriberTypeData = transcriberTypeData;
	}

	public DoctorData getDoctordata() {
		return this.doctorData;
	}

	public void setDoctordata(DoctorData doctorData) {
		this.doctorData = doctorData;
	}

	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

}
