package com.manoinfoways.model;
// Generated Mar 22, 2012 6:27:47 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TranscriberData generated by hbm2java
 */
public class TranscriberData  implements java.io.Serializable {


     private Integer transcriberId;
     private TranscriberTypeData transcriberTypeData;
     private String password;
     private String transcriberName;
     private Date dateofJoining;
     private String transcriberAddress;
     private String transcriberPermanentAddress;
     private Integer transcriberPhnNuber;
     private Integer transcriberMobile;
     private String transcriberEmail;
     private String transcriberQualification;
     private String transcriberExperience;
     private Date transcriberDob;
     private Date transcriberLoginTime;
     private Set<VoiceFilesData> voiceFilesDatas = new HashSet<VoiceFilesData>(0);

    public TranscriberData() {
    }

    public TranscriberData(TranscriberTypeData transcriberTypeData, String password, String transcriberName, Date dateofJoining, String transcriberAddress, String transcriberPermanentAddress, Integer transcriberPhnNuber, Integer transcriberMobile, String transcriberEmail, String transcriberQualification, String transcriberExperience, Date transcriberDob, Date transcriberLoginTime, Set<VoiceFilesData> voiceFilesDatas) {
       this.transcriberTypeData = transcriberTypeData;
       this.password = password;
       this.transcriberName = transcriberName;
       this.dateofJoining = dateofJoining;
       this.transcriberAddress = transcriberAddress;
       this.transcriberPermanentAddress = transcriberPermanentAddress;
       this.transcriberPhnNuber = transcriberPhnNuber;
       this.transcriberMobile = transcriberMobile;
       this.transcriberEmail = transcriberEmail;
       this.transcriberQualification = transcriberQualification;
       this.transcriberExperience = transcriberExperience;
       this.transcriberDob = transcriberDob;
       this.transcriberLoginTime = transcriberLoginTime;
       this.voiceFilesDatas = voiceFilesDatas;
    }
   
    public Integer getTranscriberId() {
        return this.transcriberId;
    }
    
    public void setTranscriberId(Integer transcriberId) {
        this.transcriberId = transcriberId;
    }
    public TranscriberTypeData getTranscribertypedata() {
        return this.transcriberTypeData;
    }
    
    public void setTranscribertypedata(TranscriberTypeData transcriberTypeData) {
        this.transcriberTypeData = transcriberTypeData;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getTranscriberName() {
        return this.transcriberName;
    }
    
    public void setTranscriberName(String transcriberName) {
        this.transcriberName = transcriberName;
    }
    public Date getDateofJoining() {
        return this.dateofJoining;
    }
    
    public void setDateofJoining(Date dateofJoining) {
        this.dateofJoining = dateofJoining;
    }
    public String getTranscriberAddress() {
        return this.transcriberAddress;
    }
    
    public void setTranscriberAddress(String transcriberAddress) {
        this.transcriberAddress = transcriberAddress;
    }
    public String getTranscriberPermanentAddress() {
        return this.transcriberPermanentAddress;
    }
    
    public void setTranscriberPermanentAddress(String transcriberPermanentAddress) {
        this.transcriberPermanentAddress = transcriberPermanentAddress;
    }
    public Integer getTranscriberPhnNuber() {
        return this.transcriberPhnNuber;
    }
    
    public void setTranscriberPhnNuber(Integer transcriberPhnNuber) {
        this.transcriberPhnNuber = transcriberPhnNuber;
    }
    public Integer getTranscriberMobile() {
        return this.transcriberMobile;
    }
    
    public void setTranscriberMobile(Integer transcriberMobile) {
        this.transcriberMobile = transcriberMobile;
    }
    public String getTranscriberEmail() {
        return this.transcriberEmail;
    }
    
    public void setTranscriberEmail(String transcriberEmail) {
        this.transcriberEmail = transcriberEmail;
    }
    public String getTranscriberQualification() {
        return this.transcriberQualification;
    }
    
    public void setTranscriberQualification(String transcriberQualification) {
        this.transcriberQualification = transcriberQualification;
    }
    public String getTranscriberExperience() {
        return this.transcriberExperience;
    }
    
    public void setTranscriberExperience(String transcriberExperience) {
        this.transcriberExperience = transcriberExperience;
    }
    public Date getTranscriberDob() {
        return this.transcriberDob;
    }
    
    public void setTranscriberDob(Date transcriberDob) {
        this.transcriberDob = transcriberDob;
    }
    public Date getTranscriberLoginTime() {
        return this.transcriberLoginTime;
    }
    
    public void setTranscriberLoginTime(Date transcriberLoginTime) {
        this.transcriberLoginTime = transcriberLoginTime;
    }
    public Set<VoiceFilesData> getVoicefilesdatas() {
        return this.voiceFilesDatas;
    }
    
    public void setVoicefilesdatas(Set<VoiceFilesData> voiceFilesDatas) {
        this.voiceFilesDatas = voiceFilesDatas;
    }




}


