package com.manoinfoways.model;

// Generated Mar 30, 2012 7:20:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * ClinicRequirements generated by hbm2java
 */
public class ClinicRequirements implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7854678149152475312L;
	private Integer clinicRequirementId;
	private ClinicData clinicData;
	private String clinicRequirement;

	public ClinicRequirements() {
	}

	public ClinicRequirements(ClinicData clinicData) {
		this.clinicData = clinicData;
	}

	public ClinicRequirements(ClinicData clinicData, String clinicRequirement) {
		this.clinicData = clinicData;
		this.clinicRequirement = clinicRequirement;
	}

	public Integer getClinicRequirementId() {
		return this.clinicRequirementId;
	}

	public void setClinicRequirementId(Integer clinicRequirementId) {
		this.clinicRequirementId = clinicRequirementId;
	}

	public ClinicData getClinicdata() {
		return this.clinicData;
	}

	public void setClinicdata(ClinicData clinicData) {
		this.clinicData = clinicData;
	}

	public String getClinicRequirement() {
		return this.clinicRequirement;
	}

	public void setClinicRequirement(String clinicRequirement) {
		this.clinicRequirement = clinicRequirement;
	}

}
