package com.manoinfoways.model;

// Generated Mar 30, 2012 7:20:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;


/**
 * ClinicData generated by hbm2java
 */
public class ClinicData implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -610097620615224676L;
	private Integer clinicId;
	private ClinicMetadata clinicMetadata;
	private ClinicConnectionDetails clinicConnectionDetails;
	private String clinicAbbr;
	private String clinicName;
	private String addressLine1;
	private String addressLine2;
	private String country;
	private String location;
	private Integer zipcode;
	
	private Set<InboundVoiceFilesData> inboundVoiceFilesDatas = new HashSet<InboundVoiceFilesData>(
			0);
	
	private Set<DoctorData> doctorDatas = new HashSet<DoctorData>(0);
	
	private Set<ClinicRequirements> clinicrequirementses = new HashSet<ClinicRequirements>(
			0);

	public ClinicData() {
	}
	
	public ClinicData(Integer clinicId, String clinicAbbr) {
		this.clinicId = clinicId;
		this.clinicAbbr = clinicAbbr;
	}
	
	public ClinicData(String clinicAbbr) {
		this.clinicAbbr = clinicAbbr;
	}

	public ClinicData(ClinicMetadata clinicMetadata,
			ClinicConnectionDetails clinicConnectionDetails, String clinicAbbr,
			String clinicName, String addressLine1, String addressLine2,
			String country, String location, Integer zipcode) {
		this.clinicMetadata = clinicMetadata;
		this.clinicConnectionDetails = clinicConnectionDetails;
		this.clinicAbbr = clinicAbbr;
		this.clinicName = clinicName;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.country = country;
		this.location = location;
		this.zipcode = zipcode;
	}

	public ClinicData(int clinicId) {
		this.clinicId = clinicId;
	}

	public Integer getClinicId() {
		return this.clinicId;
	}

	public void setClinicId(Integer clinicId) {
		this.clinicId = clinicId;
	}

	public ClinicMetadata getClinicmetadata() {
		return this.clinicMetadata;
	}

	public void setClinicmetadata(ClinicMetadata clinicMetadata) {
		this.clinicMetadata = clinicMetadata;
	}

	public ClinicConnectionDetails getClinicconnectiondetails() {
		return this.clinicConnectionDetails;
	}

	public void setClinicconnectiondetails(
			ClinicConnectionDetails clinicConnectionDetails) {
		this.clinicConnectionDetails = clinicConnectionDetails;
	}

	public String getClinicAbbr() {
		return this.clinicAbbr;
	}

	public void setClinicAbbr(String clinicAbbr) {
		this.clinicAbbr = clinicAbbr;
	}

	public String getClinicName() {
		return this.clinicName;
	}

	public void setClinicName(String clinicName) {
		this.clinicName = clinicName;
	}

	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Integer getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(Integer zipcode) {
		this.zipcode = zipcode;
	}

	public Set<InboundVoiceFilesData> getInboundvoicefilesdatas() {
		return this.inboundVoiceFilesDatas;
	}

	public void setInboundvoicefilesdatas(
			Set<InboundVoiceFilesData> inboundVoiceFilesDatas) {
		this.inboundVoiceFilesDatas = inboundVoiceFilesDatas;
	}

	public Set<DoctorData> getDoctordatas() {
		return this.doctorDatas;
	}

	public void setDoctordatas(Set<DoctorData> doctorDatas) {
		this.doctorDatas = doctorDatas;
	}

	public Set<ClinicRequirements> getClinicrequirementses() {
		return this.clinicrequirementses;
	}

	public void setClinicrequirementses(
			Set<ClinicRequirements> clinicrequirementses) {
		this.clinicrequirementses = clinicrequirementses;
	}

}
