package com.manoinfoways.model;
// Generated Mar 22, 2012 6:27:47 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * ClinicData generated by hbm2java
 */
public class ClinicData  implements java.io.Serializable {


     private Integer clinicId;
     private String clinicAbbr;
     private String clinicName;
     private String addressLine1;
     private String addressLine2;
     private String country;
     private String location;
     private Integer zipcode;
     private Set<VoiceFilesData> voiceFilesDatas = new HashSet<VoiceFilesData>(0);
     private Set<DoctorData> doctorDatas = new HashSet<DoctorData>(0);
     private Set<ClinicRequirements> clinicrequirementses = new HashSet<ClinicRequirements>(0);
     private Set<ClinicConnectionDetails> clinicconnectiondetailses = new HashSet<ClinicConnectionDetails>(0);
     private Set<ClinicMetadata> clinicMetadatas = new HashSet<ClinicMetadata>(0);

    public ClinicData() {
    }

	
    public ClinicData(String clinicAbbr) {
        this.clinicAbbr = clinicAbbr;
    }
    public ClinicData(String clinicAbbr, String clinicName, String addressLine1, String addressLine2, String country, String location, Integer zipcode, Set<VoiceFilesData> voiceFilesDatas, Set<DoctorData> doctorDatas, Set<ClinicRequirements> clinicrequirementses, Set<ClinicConnectionDetails> clinicconnectiondetailses, Set<ClinicMetadata> clinicMetadatas) {
       this.clinicAbbr = clinicAbbr;
       this.clinicName = clinicName;
       this.addressLine1 = addressLine1;
       this.addressLine2 = addressLine2;
       this.country = country;
       this.location = location;
       this.zipcode = zipcode;
       this.voiceFilesDatas = voiceFilesDatas;
       this.doctorDatas = doctorDatas;
       this.clinicrequirementses = clinicrequirementses;
       this.clinicconnectiondetailses = clinicconnectiondetailses;
       this.clinicMetadatas = clinicMetadatas;
    }
   
    public Integer getClinicId() {
        return this.clinicId;
    }
    
    public void setClinicId(Integer clinicId) {
        this.clinicId = clinicId;
    }
    public String getClinicAbbr() {
        return this.clinicAbbr;
    }
    
    public void setClinicAbbr(String clinicAbbr) {
        this.clinicAbbr = clinicAbbr;
    }
    public String getClinicName() {
        return this.clinicName;
    }
    
    public void setClinicName(String clinicName) {
        this.clinicName = clinicName;
    }
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public Integer getZipcode() {
        return this.zipcode;
    }
    
    public void setZipcode(Integer zipcode) {
        this.zipcode = zipcode;
    }
    public Set<VoiceFilesData> getVoicefilesdatas() {
        return this.voiceFilesDatas;
    }
    
    public void setVoicefilesdatas(Set<VoiceFilesData> voiceFilesDatas) {
        this.voiceFilesDatas = voiceFilesDatas;
    }
    public Set<DoctorData> getDoctordatas() {
        return this.doctorDatas;
    }
    
    public void setDoctordatas(Set<DoctorData> doctorDatas) {
        this.doctorDatas = doctorDatas;
    }
    public Set<ClinicRequirements> getClinicrequirementses() {
        return this.clinicrequirementses;
    }
    
    public void setClinicrequirementses(Set<ClinicRequirements> clinicrequirementses) {
        this.clinicrequirementses = clinicrequirementses;
    }
    public Set<ClinicConnectionDetails> getClinicconnectiondetailses() {
        return this.clinicconnectiondetailses;
    }
    
    public void setClinicconnectiondetailses(Set<ClinicConnectionDetails> clinicconnectiondetailses) {
        this.clinicconnectiondetailses = clinicconnectiondetailses;
    }
    public Set<ClinicMetadata> getClinicmetadatas() {
        return this.clinicMetadatas;
    }
    
    public void setClinicmetadatas(Set<ClinicMetadata> clinicMetadatas) {
        this.clinicMetadatas = clinicMetadatas;
    }




}


