package com.manoinfoways.model;

// Generated Apr 13, 2012 2:07:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * DoctorData generated by hbm2java
 */
public class DoctorData implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8889589954061182966L;
	private Integer doctorId;
	private ClinicData clinicData;
	private String doctorAbbr;
	private String doctorName;
	private String doctorTollFreeId;
	private String doctorResourceId;
	private String doctorComputerTagsIp;
	private Set<TranscriberDoctorPriority> transcriberDoctorPriorities = new HashSet<TranscriberDoctorPriority>(
			0);
	private Set<VoiceFilesAssignmentData> voiceFilesAssignmentDatas = new HashSet<VoiceFilesAssignmentData>(
			0);
	private Set<InboundVoiceFilesData> inboundVoiceFilesDatas = new HashSet<InboundVoiceFilesData>(
			0);

	public DoctorData() {
	}

	public DoctorData(String doctorAbbr) {
		this.doctorAbbr = doctorAbbr;
	}

	public DoctorData(ClinicData clinicData, String doctorAbbr,
			String doctorName, String doctorTollFreeId,
			String doctorResourceId, String doctorComputerTagsIp,
			Set<TranscriberDoctorPriority> transcriberDoctorPriorities,
			Set<VoiceFilesAssignmentData> voiceFilesAssignmentDatas,
			Set<InboundVoiceFilesData> inboundVoiceFilesDatas) {
		this.clinicData = clinicData;
		this.doctorAbbr = doctorAbbr;
		this.doctorName = doctorName;
		this.doctorTollFreeId = doctorTollFreeId;
		this.doctorResourceId = doctorResourceId;
		this.doctorComputerTagsIp = doctorComputerTagsIp;
		this.transcriberDoctorPriorities = transcriberDoctorPriorities;
		this.voiceFilesAssignmentDatas = voiceFilesAssignmentDatas;
		this.inboundVoiceFilesDatas = inboundVoiceFilesDatas;
	}

	public Integer getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(Integer doctorId) {
		this.doctorId = doctorId;
	}

	public ClinicData getClinicdata() {
		return this.clinicData;
	}

	public void setClinicdata(ClinicData clinicData) {
		this.clinicData = clinicData;
	}

	public String getDoctorAbbr() {
		return this.doctorAbbr;
	}

	public void setDoctorAbbr(String doctorAbbr) {
		this.doctorAbbr = doctorAbbr;
	}

	public String getDoctorName() {
		return this.doctorName;
	}

	public void setDoctorName(String doctorName) {
		this.doctorName = doctorName;
	}

	public String getDoctorTollFreeId() {
		return this.doctorTollFreeId;
	}

	public void setDoctorTollFreeId(String doctorTollFreeId) {
		this.doctorTollFreeId = doctorTollFreeId;
	}

	public String getDoctorResourceId() {
		return this.doctorResourceId;
	}

	public void setDoctorResourceId(String doctorResourceId) {
		this.doctorResourceId = doctorResourceId;
	}

	public String getDoctorComputerTagsIp() {
		return this.doctorComputerTagsIp;
	}

	public void setDoctorComputerTagsIp(String doctorComputerTagsIp) {
		this.doctorComputerTagsIp = doctorComputerTagsIp;
	}

	public Set<TranscriberDoctorPriority> getTranscriberdoctorpriorities() {
		return this.transcriberDoctorPriorities;
	}

	public void setTranscriberdoctorpriorities(
			Set<TranscriberDoctorPriority> transcriberDoctorPriorities) {
		this.transcriberDoctorPriorities = transcriberDoctorPriorities;
	}

	public Set<VoiceFilesAssignmentData> getVoicefilesassignmentdatas() {
		return this.voiceFilesAssignmentDatas;
	}

	public void setVoicefilesassignmentdatas(
			Set<VoiceFilesAssignmentData> voiceFilesAssignmentDatas) {
		this.voiceFilesAssignmentDatas = voiceFilesAssignmentDatas;
	}

	public Set<InboundVoiceFilesData> getInboundvoicefilesdatas() {
		return this.inboundVoiceFilesDatas;
	}

	public void setInboundvoicefilesdatas(
			Set<InboundVoiceFilesData> inboundVoiceFilesDatas) {
		this.inboundVoiceFilesDatas = inboundVoiceFilesDatas;
	}

}
