package com.manoinfoways.model;
// Generated Mar 22, 2012 6:27:47 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * TranscriberTypeData generated by hbm2java
 */
public class TranscriberTypeData  implements java.io.Serializable {


     private Integer transcriberTypeId;
     private String transcriberTypeName;
     private Set<TranscriberData> transcriberDatas = new HashSet<TranscriberData>(0);

    public TranscriberTypeData() {
    }

    public TranscriberTypeData(String transcriberTypeName, Set<TranscriberData> transcriberDatas) {
       this.transcriberTypeName = transcriberTypeName;
       this.transcriberDatas = transcriberDatas;
    }
   
    public Integer getTranscriberTypeId() {
        return this.transcriberTypeId;
    }
    
    public void setTranscriberTypeId(Integer transcriberTypeId) {
        this.transcriberTypeId = transcriberTypeId;
    }
    public String getTranscriberTypeName() {
        return this.transcriberTypeName;
    }
    
    public void setTranscriberTypeName(String transcriberTypeName) {
        this.transcriberTypeName = transcriberTypeName;
    }
    public Set<TranscriberData> getTranscriberdatas() {
        return this.transcriberDatas;
    }
    
    public void setTranscriberdatas(Set<TranscriberData> transcriberDatas) {
        this.transcriberDatas = transcriberDatas;
    }




}


