package com.manoinfoways.model;

// Generated May 16, 2012 12:58:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transcriberdata generated by hbm2java
 */
public class TranscriberData implements java.io.Serializable {

	private Integer transcriberId;
	private TranscriberTypeData transcribertypedata;
	private String userName;
	private String password;
	private String transcriberName;
	private Date dateofJoining;
	private String transcriberAddress;
	private String transcriberPermanentAddress;
	private String transcriberPhoneNumber;
	private String transcriberMobile;
	private String transcriberEmail;
	private String transcriberQualification;
	private String transcriberExperience;
	private Date transcriberDob;
	private Date transcriberLoginTime;
	private Set<TranscriberLengthTimes> transcriberlengthtimeses = new HashSet<TranscriberLengthTimes>(
			0);

	public TranscriberData() {
	}

	public TranscriberData(TranscriberTypeData transcribertypedata,
			String userName, String password, String transcriberName,
			Date dateofJoining, String transcriberAddress,
			String transcriberPermanentAddress, String transcriberPhoneNumber,
			String transcriberMobile, String transcriberEmail,
			String transcriberQualification, String transcriberExperience,
			Date transcriberDob, Date transcriberLoginTime,
			Set<TranscriberLengthTimes> transcriberlengthtimeses) {
		this.transcribertypedata = transcribertypedata;
		this.userName = userName;
		this.password = password;
		this.transcriberName = transcriberName;
		this.dateofJoining = dateofJoining;
		this.transcriberAddress = transcriberAddress;
		this.transcriberPermanentAddress = transcriberPermanentAddress;
		this.transcriberPhoneNumber = transcriberPhoneNumber;
		this.transcriberMobile = transcriberMobile;
		this.transcriberEmail = transcriberEmail;
		this.transcriberQualification = transcriberQualification;
		this.transcriberExperience = transcriberExperience;
		this.transcriberDob = transcriberDob;
		this.transcriberLoginTime = transcriberLoginTime;
		this.transcriberlengthtimeses = transcriberlengthtimeses;
	}

	public Integer getTranscriberId() {
		return this.transcriberId;
	}

	public void setTranscriberId(Integer transcriberId) {
		this.transcriberId = transcriberId;
	}

	public TranscriberTypeData getTranscribertypedata() {
		return this.transcribertypedata;
	}

	public void setTranscribertypedata(TranscriberTypeData transcribertypedata) {
		this.transcribertypedata = transcribertypedata;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getTranscriberName() {
		return this.transcriberName;
	}

	public void setTranscriberName(String transcriberName) {
		this.transcriberName = transcriberName;
	}

	public Date getDateofJoining() {
		return this.dateofJoining;
	}

	public void setDateofJoining(Date dateofJoining) {
		this.dateofJoining = dateofJoining;
	}

	public String getTranscriberAddress() {
		return this.transcriberAddress;
	}

	public void setTranscriberAddress(String transcriberAddress) {
		this.transcriberAddress = transcriberAddress;
	}

	public String getTranscriberPermanentAddress() {
		return this.transcriberPermanentAddress;
	}

	public void setTranscriberPermanentAddress(
			String transcriberPermanentAddress) {
		this.transcriberPermanentAddress = transcriberPermanentAddress;
	}

	public String getTranscriberPhoneNumber() {
		return this.transcriberPhoneNumber;
	}

	public void setTranscriberPhoneNumber(String transcriberPhoneNumber) {
		this.transcriberPhoneNumber = transcriberPhoneNumber;
	}

	public String getTranscriberMobile() {
		return this.transcriberMobile;
	}

	public void setTranscriberMobile(String transcriberMobile) {
		this.transcriberMobile = transcriberMobile;
	}

	public String getTranscriberEmail() {
		return this.transcriberEmail;
	}

	public void setTranscriberEmail(String transcriberEmail) {
		this.transcriberEmail = transcriberEmail;
	}

	public String getTranscriberQualification() {
		return this.transcriberQualification;
	}

	public void setTranscriberQualification(String transcriberQualification) {
		this.transcriberQualification = transcriberQualification;
	}

	public String getTranscriberExperience() {
		return this.transcriberExperience;
	}

	public void setTranscriberExperience(String transcriberExperience) {
		this.transcriberExperience = transcriberExperience;
	}

	public Date getTranscriberDob() {
		return this.transcriberDob;
	}

	public void setTranscriberDob(Date transcriberDob) {
		this.transcriberDob = transcriberDob;
	}

	public Date getTranscriberLoginTime() {
		return this.transcriberLoginTime;
	}

	public void setTranscriberLoginTime(Date transcriberLoginTime) {
		this.transcriberLoginTime = transcriberLoginTime;
	}

	public Set<TranscriberLengthTimes> getTranscriberlengthtimeses() {
		return this.transcriberlengthtimeses;
	}

	public void setTranscriberlengthtimeses(
			Set<TranscriberLengthTimes> transcriberlengthtimeses) {
		this.transcriberlengthtimeses = transcriberlengthtimeses;
	}

}
