package com.manoinfoways.model;

// Generated Mar 14, 2012 4:42:37 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * VoiceFilesData generated by hbm2java
 */
public class VoiceFilesData implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 285290050598618783L;
	private String fileId;
	private TranscriberData transcriberData;
	private DoctorData doctorData;
	private ClinicData clinicData;
	private Date dateOfDictation;
	private BigDecimal lengthOfFile;

	public VoiceFilesData() {
	}

	public VoiceFilesData(String fileId) {
		this.fileId = fileId;
	}

	public VoiceFilesData(String fileId, TranscriberData transcriberData,
			DoctorData doctorData, ClinicData clinicData, Date dateOfDictation,
			BigDecimal lengthOfFile) {
		this.fileId = fileId;
		this.transcriberData = transcriberData;
		this.doctorData = doctorData;
		this.clinicData = clinicData;
		this.dateOfDictation = dateOfDictation;
		this.lengthOfFile = lengthOfFile;
	}

	public String getFileId() {
		return this.fileId;
	}

	public void setFileId(String fileId) {
		this.fileId = fileId;
	}

	public TranscriberData getTranscriberdata() {
		return this.transcriberData;
	}

	public void setTranscriberdata(TranscriberData transcriberData) {
		this.transcriberData = transcriberData;
	}

	public DoctorData getDoctordata() {
		return this.doctorData;
	}

	public void setDoctordata(DoctorData doctorData) {
		this.doctorData = doctorData;
	}

	public ClinicData getClinicdata() {
		return this.clinicData;
	}

	public void setClinicdata(ClinicData clinicData) {
		this.clinicData = clinicData;
	}

	public Date getDateOfDictation() {
		return this.dateOfDictation;
	}

	public void setDateOfDictation(Date dateOfDictation) {
		this.dateOfDictation = dateOfDictation;
	}

	public BigDecimal getLengthOfFile() {
		return this.lengthOfFile;
	}

	public void setLengthOfFile(BigDecimal lengthOfFile) {
		this.lengthOfFile = lengthOfFile;
	}

}
