package com.manoinfoways.model;

// Generated Apr 13, 2012 2:07:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * VoiceFilesAssignmentData generated by hbm2java
 */
public class VoiceFilesAssignmentData implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1336383383270723735L;
	private Integer fileAssignmentId;
	private TranscriberData transcriberdataByTranscriberId;
	private InboundVoiceFilesData inboundVoiceFilesData;
	private TranscriberData transcriberdataByEditorId;
	private TranscriberData transcriberdataByProoferId;
	private DoctorData doctorData;
	private TranscriberData transcriberdataByQaid;
	private Set<FileTransactionData> fileTransactionDatas = new HashSet<FileTransactionData>(
			0);

	public VoiceFilesAssignmentData() {
	}

	public VoiceFilesAssignmentData(InboundVoiceFilesData inboundVoiceFilesData) {
		this.inboundVoiceFilesData = inboundVoiceFilesData;
	}

	public VoiceFilesAssignmentData(
			TranscriberData transcriberdataByTranscriberId,
			InboundVoiceFilesData inboundVoiceFilesData,
			TranscriberData transcriberdataByEditorId,
			TranscriberData transcriberdataByProoferId, DoctorData doctorData,
			TranscriberData transcriberdataByQaid,
			Set<FileTransactionData> fileTransactionDatas) {
		this.transcriberdataByTranscriberId = transcriberdataByTranscriberId;
		this.inboundVoiceFilesData = inboundVoiceFilesData;
		this.transcriberdataByEditorId = transcriberdataByEditorId;
		this.transcriberdataByProoferId = transcriberdataByProoferId;
		this.doctorData = doctorData;
		this.transcriberdataByQaid = transcriberdataByQaid;
		this.fileTransactionDatas = fileTransactionDatas;
	}

	public Integer getFileAssignmentId() {
		return this.fileAssignmentId;
	}

	public void setFileAssignmentId(Integer fileAssignmentId) {
		this.fileAssignmentId = fileAssignmentId;
	}

	public TranscriberData getTranscriberdataByTranscriberId() {
		return this.transcriberdataByTranscriberId;
	}

	public void setTranscriberdataByTranscriberId(
			TranscriberData transcriberdataByTranscriberId) {
		this.transcriberdataByTranscriberId = transcriberdataByTranscriberId;
	}

	public InboundVoiceFilesData getInboundvoicefilesdata() {
		return this.inboundVoiceFilesData;
	}

	public void setInboundvoicefilesdata(
			InboundVoiceFilesData inboundVoiceFilesData) {
		this.inboundVoiceFilesData = inboundVoiceFilesData;
	}

	public TranscriberData getTranscriberdataByEditorId() {
		return this.transcriberdataByEditorId;
	}

	public void setTranscriberdataByEditorId(
			TranscriberData transcriberdataByEditorId) {
		this.transcriberdataByEditorId = transcriberdataByEditorId;
	}

	public TranscriberData getTranscriberdataByProoferId() {
		return this.transcriberdataByProoferId;
	}

	public void setTranscriberdataByProoferId(
			TranscriberData transcriberdataByProoferId) {
		this.transcriberdataByProoferId = transcriberdataByProoferId;
	}

	public DoctorData getDoctordata() {
		return this.doctorData;
	}

	public void setDoctordata(DoctorData doctorData) {
		this.doctorData = doctorData;
	}

	public TranscriberData getTranscriberdataByQaid() {
		return this.transcriberdataByQaid;
	}

	public void setTranscriberdataByQaid(TranscriberData transcriberdataByQaid) {
		this.transcriberdataByQaid = transcriberdataByQaid;
	}

	public Set<FileTransactionData> getFiletransactiondatas() {
		return this.fileTransactionDatas;
	}

	public void setFiletransactiondatas(
			Set<FileTransactionData> fileTransactionDatas) {
		this.fileTransactionDatas = fileTransactionDatas;
	}

}
